require('dotenv').config();

const { PrismaClient } = require('@prisma/client');

const databaseUrl = process.env.DATABASE_URL;
const prisma = new PrismaClient();

async function main() {
  console.log('--- Starting Data Seeding ---');
  // ... rest of your original seeding logic ...

  let center = await prisma.center.findFirst({
    where: { name: 'Admin' },
  });

  if (!center) {
    center = await prisma.center.create({ data: { name: 'Admin' } });
    console.log('✅ Center created:', center);
  } else {
    console.log('✅ Center found:', center);
  }
/*
  try {
    const user = await prisma.user.create({
      data: {
        userName: 'startup',
        passWord: '$2b$10$y.MX6SXhoTDim.mASUeOqOwrZWMNwmNaVzjXKtv9Kl4DeajCBPPKS',
        role: 'admin',
        name: 'offline',
        idCenter: center.idCenter,
      },
    });
    console.log('✅ User created:', user);
  } catch (e) {
    console.error('⚠️ Could not create user. User might already exist.');
  }

  // Add "No medicine taken" medicine
  try {
    const noMedicine = await prisma.medicine.upsert({
      where: { name: 'No medicine taken' }, // Use name as a unique identifier for upsert
      update: {}, // No updates needed if it exists
      create: {
        name: 'No medicine taken',
        type: 'pills',
        amount: null, // Explicitly set to null as per schema (Int?)
      },
    });
    console.log('✅ Medicine "No medicine taken" added/found:', noMedicine);
  } catch (e) {
    console.error('⚠️ Could not create/find "No medicine taken" medicine:', e.message);
  }
*/
  const medicinesToAdd = [
      { name: "DEXAMETHASONE 5 g (OINTMENT)", type: "CREAM" },
  { name: "PERMETHRINE 1% 100ml (SHAMPOO)", type: "OTHER" },
  { name: "CALAMINE + ZINC OXIDE 15% + 5%, 100 ml (LOTION/LIQUID)", type: "OTHER" },
  { name: "SCAR Gel 15 g (GEL)", type: "CREAM" },
  { name: "OLAPATADINE 1MG/1ML 5 ML (EYE DROP)", type: "OTHER" },
  { name: "BECLOMETHASONE DIP. 250 MCG, 200 DOSE (INHALER)", type: "OTHER" },
  { name: "SALBUTAMOL 2 mg / 5 ml, 150 ml", type: "SYRUP" },
  { name: "AMOXYCILLIN + CLAVULANIC ACID 125mg + 31.25 mg (SUSPENSION)", type: "OTHER" },
  { name: "METRONIDAZOLE 125 mg / 5 ml, 100 ml (SUSPENSION)", type: "OTHER" },
  { name: "PARACETAMOL 125 mg / 5 ml, 100 ml (SUSPENSION)", type: "OTHER" },
  { name: "IBUPROFEN 100 mg / 5 ml, 100 ml (SUSP.)", type: "OTHER" },
  { name: "AMOXYCILLIN 125MG / 100ML (SUSPENSION)", type: "OTHER" },
  { name: "GENTAMICIN 0.3%, 5 ml (EYE DROP)", type: "OTHER" },
  { name: "ZINC OXIDE -", type: "CREAM" },
  { name: "Rupatadine 1mg/ml, 120ml (SOLUTION)", type: "OTHER" },
  { name: "STERILE OPHTHALMIC OINT (TOBRAMYCIN with DEXAMETHASONE) 5 g (EYE OINTMENT)", type: "OTHER" },
  { name: "AMOXICILLIN + CLAVULANIC ACID 500mg + 125 mg", type: "TABLET" },
  { name: "AMOXICILLIN + CLAVULANIC ACID (AUGMENTIN) 875mg + 125mg", type: "TABLET" },
  { name: "CETRIZINE 10mg", type: "TABLET" },
  { name: "FERROUS SULF + FOLIC ACID 160 mg + 400 mcg", type: "TABLET" },
  { name: "Telmisartan / Hydrochlorothiazide 40 / 12.5 mg", type: "TABLET" },
  { name: "Rosuvastatin 5 mg", type: "TABLET" },
  { name: "BISOPROLOL 5 mg", type: "TABLET" },
  { name: "BISOPROLOL 10 mg", type: "TABLET" },
  { name: "FOLIC ACID 5 mg", type: "TABLET" },
  { name: "METFORMIN 500MG", type: "TABLET" },
  { name: "AMIODARONE HCl 200 mg", type: "TABLET" },
  { name: "FUROSEMIDE 40 mg", type: "TABLET" },
  { name: "GLIMEPRIIDE 2 mg", type: "TABLET" },
  { name: "ENALAPRIL 10mg", type: "TABLET" },
  { name: "MULTIVITAMINES -", type: "TABLET" },
  { name: "METRONIDAZOLE 250 mg", type: "TABLET" },
  { name: "METRONIDAZOLE 500MG", type: "TABLET" },
  { name: "DICLOFENAC SODIUM 50 mg", type: "TABLET" },
  { name: "ISOSORBIDE 5- MONONITRATE 20 mg", type: "TABLET" },
  { name: "WARFARIN SODIUM 5 mg", type: "TABLET" },
  { name: "AMLODIPINE + VALSARTAN 5/160 mg", type: "TABLET" },
  { name: "VALSARTAN + AMLODIPINE 160mg / 10mg", type: "TABLET" },
  { name: "VALSARTAN HCT 160 / 12.5 mg", type: "TABLET" },
  { name: "SPASMODIGESTIN -", type: "TABLET" },
  { name: "GLICLAZIDE 80 mg", type: "TABLET" },
  { name: "VERAPAMIL HCl 40 mg", type: "TABLET" },
  { name: "CLOPIDOGREL 75 mg", type: "TABLET" },
  { name: "HYDROCHLORTHIAZIDE 25mg", type: "TABLET" },
  { name: "PARACETAMOL 500 mg", type: "TABLET" },
  { name: "IBUPROFEN 400 MG", type: "TABLET" },
  { name: "LORATADINE 10mg", type: "TABLET" },
  { name: "CEFADROXIL 500 MG", type: "TABLET" },
  { name: "OMEPRAZOLE 20 mg", type: "CAPSULE" },
  { name: "Etoricoxib 60mg", type: "TABLET" },
  { name: "ETORICOXIB 90mg", type: "TABLET" },
  { name: "ALBENDAZOLE 400mg", type: "TABLET" },
  { name: "ALBENDAZOLE 200 MG", type: "TABLET" },
  { name: "ACETYLSALICYLIC ACID (ASPIRIN) 100 mg", type: "TABLET" },
  { name: "Telmisartan / Hydrochlorothiazide 80 / 12.5 mg", type: "TABLET" },
  { name: "LOSARTAN 50 mg", type: "TABLET" },
  { name: "LOSARTAN 100 mg", type: "TABLET" },
  { name: "DOXYCYCLINE 100 mg", type: "TABLET" },
  { name: "MONTELUKAST 10 mg", type: "TABLET" },
  { name: "Montelukast Sodium 5 mg", type: "TABLET" },
  { name: "ROSUVASTATIN 20 MG", type: "TABLET" },
  { name: "CLARITHROMYCINE 500 MG", type: "TABLET" },
  { name: "Mebendazole 500 mg (CHEWABLE TAB)", type: "OTHER" },
  { name: "NITROFURANTOIN 100mg", type: "CAPSULE" },
  { name: "ATORVASTATIN 20 mg", type: "TABLET" },
  { name: "PARACETAMOL 160 mg / 5 ml, 100 ml (SUSPENSION)", type: "OTHER" },
  { name: "PARACETAMOL 250 mg / 5 ml, 60 (SUSPENSION)", type: "OTHER" },
  { name: "Loratadine 5 mg / 5 ml, 60 ml", type: "SYRUP" },
  { name: "VALSARTAN HCT 80 / 12.5 mg", type: "TABLET" },
  { name: "Erythromycin nan (SUSPENSION)", type: "OTHER" },
  { name: "nan nan (NAN)", type: "OTHER" },
  { name: "Captopril 50mg", type: "TABLET" },
  { name: "Captopril 25mg", type: "TABLET" },
  { name: "Enalapril 5mg", type: "TABLET" },
  { name: "Enalapril 10mg", type: "TABLET" },
  { name: "Enalapril 20mg", type: "TABLET" },
  { name: "Ramipril 2.5 mg", type: "TABLET" },
  { name: "Ramipril 5 mg", type: "TABLET" },
  { name: "Ramipril HCT 2.5/12.5 mg", type: "TABLET" },
  { name: "Ramipril HCT 5/25 mg", type: "TABLET" },
  { name: "Losartan+HTC 50/12.5mg", type: "TABLET" },
  { name: "Candisartan 8 mg", type: "TABLET" },
  { name: "Candisartan 16 mg", type: "TABLET" },
  { name: "Candisartan+HTC 16/12.5mg", type: "TABLET" },
  { name: "Valsartan 80 mg", type: "TABLET" },
  { name: "Valsartan 160 mg", type: "TABLET" },
  { name: "Valsartan+HCT 80/12.5mg", type: "TABLET" },
  { name: "Valsartan+HCT 160/12.5mg", type: "TABLET" },
  { name: "Valsartan+HCT 160/25 mg", type: "TABLET" },
  { name: "Valsartan+HCT 320/25 mg", type: "TABLET" },
  { name: "valsartan+amlodipine 80/5 mg", type: "TABLET" },
  { name: "valsartan+amlodipine 80/10 mg", type: "TABLET" },
  { name: "valsartan+amlodipine 160/5 mg", type: "TABLET" },
  { name: "valsartan+amlodipine 160/10 mg", type: "TABLET" },
  { name: "Valsartan+HCT+ Amlodipine 160/5/12.5mg", type: "TABLET" },
  { name: "Valsartan+HCT+ Amlodipine 160/10/12.5mg", type: "TABLET" },
  { name: "Valsartan+HCT+ Amlodipine 160/10/25 mg", type: "TABLET" },
  { name: "Atenolol 100mg", type: "TABLET" },
  { name: "Atenolol 25mg", type: "TABLET" },
  { name: "Atenolol 50mg", type: "TABLET" },
  { name: "Metoprolol 100mg", type: "TABLET" },
  { name: "Labetalol 100mg", type: "TABLET" },
  { name: "Bisoprolol 5mg", type: "TABLET" },
  { name: "Bisoprolol 2.5mg", type: "TABLET" },
  { name: "Bisoprolol 10mg", type: "TABLET" },
  { name: "Carvedilol 6.25 mg", type: "TABLET" },
  { name: "Carvedilol 12.5 mg", type: "TABLET" },
  { name: "Propranolol 10mg", type: "TABLET" },
  { name: "Salbutamol - (NEBULIZER)", type: "OTHER" },
  { name: "Ipratropiumbromide - (NEBULIZER)", type: "OTHER" },
  { name: "Budisonide - (NEBULIZER)", type: "OTHER" },
  { name: "Mometasone - (NASAL SPRAY)", type: "OTHER" },
  { name: "Triamicolone - (VIAL)", type: "OTHER" },
  { name: "Dexamethasone - (AMP)", type: "OTHER" },
  { name: "Theophylline - (AMP)", type: "OTHER" },
  { name: "Triamcinolone 4 mg", type: "TABLET" },
  { name: "Methyl Prednisolone 4mg", type: "TABLET" },
  { name: "Betamethasone .5 mg", type: "TABLET" },
  { name: "Dexamethasone 2 mg", type: "TABLET" },
  { name: "Dexamethasone .5 mg", type: "TABLET" },
  { name: "Dexamethasone .75 mg", type: "TABLET" },
  { name: "Theopyline 100 mg", type: "TABLET" },
  { name: "Theopyline 300 mg", type: "TABLET" },
  { name: "Montelukast 10 mg", type: "TABLET" },
  { name: "Montelukast 4 mg", type: "TABLET" },
  { name: "Montelukast 5 mg", type: "TABLET" },
  { name: "Budesonide 200 mg (INHALED CAPS)", type: "OTHER" },
  { name: "Budesonide 400 mg (INHALED CAPS)", type: "OTHER" },
  { name: "Fluticasone + vilanterol 184/22 (INHALER)", type: "OTHER" },
  { name: "Fluticasone + vilanterol 92/22 (INHALER)", type: "OTHER" },
  { name: "Fluticasone + Salmeterol 50/100 (INHALER)", type: "OTHER" },
  { name: "Fluticasone + Salmeterol 250/50 (INHALER)", type: "OTHER" },
  { name: "Fluticasone + Salmeterol 500/50 (INHALER)", type: "OTHER" },
  { name: "Betamethasone 1 ml (AMP)", type: "OTHER" },
  { name: "Betamethasone 2 ml (AMP)", type: "OTHER" },
  { name: "Methyl prednisolone 80mg (-)", type: "OTHER" },
  { name: "Methyl prednisolone 40 mg (VIAL)", type: "OTHER" },
  { name: "Penicillin V 250mg/5ml (SUSP)", type: "OTHER" },
  { name: "Penicillin V 500 mg", type: "TABLET" },
  { name: "Ampicillim + flucloxacillin 250 mg", type: "CAPSULE" },
  { name: "Ampicillim + flucloxacillin 500 mg", type: "CAPSULE" },
  { name: "Ampicillim + flucloxacillin 250 mg/5 ml", type: "CAPSULE" },
  { name: "Ampicillim + flucloxacillin 125mg/5 ml (SUSP)", type: "OTHER" },
  { name: "penicillin 12000000 (UI VIAL)", type: "OTHER" },
  { name: "Clavulanic acid +Amoxicillin 500 mg", type: "TABLET" },
  { name: "Clavulanic acid +Amoxicillin 875 mg", type: "TABLET" },
  { name: "Clavulanic acid +Amoxicillin 125mg/5ml (SUSP)", type: "OTHER" },
  { name: "Clavulanic acid +Amoxicillin 250mg/5ml (SUSP)", type: "OTHER" },
  { name: "Clavulanic acid +Amoxicillin 400 mg/5ml (-)", type: "OTHER" },
  { name: "Clavulanic acid +Amoxicillin 600 mg/5ml (SUSP)", type: "OTHER" },
  { name: "Amoxicillin 125mg/5 ml (SUSP)", type: "OTHER" },
  { name: "Amoxicillin 250mg/5 ml (SUSP)", type: "OTHER" },
  { name: "Amoxicillin 400 mg/5 ml (SUSP)", type: "OTHER" },
  { name: "Amoxicillin 250mg", type: "CAPSULE" },
  { name: "Amoxicillin 500mg", type: "CAPSULE" },
  { name: "Amoxicillin 1000mg", type: "CAPSULE" },
  { name: "Cephalaxin 500 mg", type: "CAPSULE" },
  { name: "Cephalaxin 750 mg", type: "CAPSULE" },
  { name: "Cephalaxin 250mg/5 ml (SUSP)", type: "OTHER" },
  { name: "Cefadroxil 250mg/5ml (SUSP)", type: "OTHER" },
  { name: "Cefadroxil 500 mg", type: "TABLET" },
  { name: "Cefuroxime 750mg (VIAL)", type: "OTHER" },
  { name: "Cefuroxime 250 mg", type: "TABLET" },
  { name: "Cefuroxime 500 mg", type: "TABLET" },
  { name: "Cefuroxime 125mg/5ml (SUSP)", type: "OTHER" },
  { name: "Cefuroxime 250mg/5ml (SUSP)", type: "OTHER" },
  { name: "Cefaclor 250mg/5ml (SUSP)", type: "OTHER" },
  { name: "Cefaclor 125mg/5ml (SUSP)", type: "OTHER" },
  { name: "Cefaclor 500 mg", type: "CAPSULE" },
  { name: "Cefdinir 300 mg", type: "TABLET" },
  { name: "Cefdinir 125mg/5ml (SUSP)", type: "OTHER" },
  { name: "Cefdinir 250mg/5ml (SUSP)", type: "OTHER" },
  { name: "Cefixime 400 mg", type: "CAPSULE" },
  { name: "Cefixime 100mg/5ml (SUSP)", type: "OTHER" },
  { name: "Ceftriaxone 1g (VIAL)", type: "OTHER" },
  { name: "Cefpodoxime 100mg", type: "TABLET" },
  { name: "Cefpodoxime 200mg", type: "TABLET" },
  { name: "Teracycline 250 mg", type: "CAPSULE" },
  { name: "Doxycycline 100mg", type: "CAPSULE" },
  { name: "Minocyline 100mg", type: "CAPSULE" },
  { name: "Minocyline 50mg", type: "CAPSULE" },
  { name: "Erythromycin 250mg", type: "TABLET" },
  { name: "Erythromycin 200mg/5ml (SUSP)", type: "OTHER" },
  { name: "Erythromycin 400mg/5ml (SUSP)", type: "OTHER" },
  { name: "Clarithromycin 125mg/5 ml (SUSP)", type: "OTHER" },
  { name: "Clarithromycin 250mg/5 ml (SUSP)", type: "OTHER" },
  { name: "Clarithromycin 500 mg", type: "TABLET" },
  { name: "Azithromycin 500 mg", type: "CAPSULE" },
  { name: "Azithromycin 250 mg", type: "CAPSULE" },
  { name: "Azithromycin 200 mg/5ml (SUSP)", type: "OTHER" },
  { name: "Roxithromycin 150 mg", type: "CAPSULE" },
  { name: "Roxithromycin 300 mg", type: "CAPSULE" },
  { name: "Spiramycin 1.5 m.u", type: "CAPSULE" },
  { name: "Clindamycin 150 mg", type: "CAPSULE" },
  { name: "Clindamycin 300 mg", type: "CAPSULE" },
  { name: "Ciprofloxacin 500 mg", type: "TABLET" },
  { name: "Ciprofloxacin 750 mg", type: "TABLET" },
  { name: "Ofloxacin 200mg", type: "TABLET" },
  { name: "Ofloxacin 500mg", type: "TABLET" },
  { name: "Levofloxacin 250 mg", type: "TABLET" },
  { name: "Levofloxacin 500 mg", type: "TABLET" },
  { name: "Levofloxacin 750 mg", type: "TABLET" },
  { name: "Moxifloxacin 400mg", type: "TABLET" },
  { name: "Gemifloxacin 320mg", type: "TABLET" },
  { name: "Rifampicin 300mg", type: "CAPSULE" },
  { name: "Sulphamethoxazole + Trimethoprim 400mg+80mg", type: "CAPSULE" },
  { name: "Sulphamethoxazole + Trimethoprim 800 mg+160 mg", type: "CAPSULE" },
  { name: "Sulphamethoxazole + Trimethoprim 200 mg+40 mg (SUSP)", type: "OTHER" },
  { name: "Linezolid 600 mg", type: "TABLET" },
  { name: "Fosfomycin 3g", type: "OTHER" },
  { name: "Fluconazole 150 mg", type: "CAPSULE" },
  { name: "Itraconazole 100mg", type: "CAPSULE" },
  { name: "Griseofulvin 125mg", type: "TABLET" },
  { name: "Terbinafine 250mg", type: "TABLET" },
  { name: "Terbinafine - (SPRAY)", type: "OTHER" },
  { name: "Terbinafine -", type: "CREAM" },
  { name: "Amantadine 100 mg", type: "TABLET" },
  { name: "Oseltamivir 75mg", type: "TABLET" },
  { name: "Acyclovir 200mg", type: "TABLET" },
  { name: "Acyclovir 800mg", type: "TABLET" },
  { name: "Acyclovir 200mg/5ml (SUSP)", type: "OTHER" },
  { name: "Mebendazole 200 mg", type: "TABLET" },
  { name: "Mebendazole 200mg/5ml (SUSP)", type: "OTHER" },
  { name: "TInidazole 500mg", type: "TABLET" },
  { name: "Metronidazole + Diloxinide 250 mg+250 mg", type: "TABLET" },
  { name: "Metronidazole + Diloxinide 125mg/5ml (SUSP)", type: "OTHER" },
  { name: "Metronidazole + Diloxinide 100 mg/5ml (SUSP)", type: "OTHER" },
  { name: "Donepezil 5 mg", type: "TABLET" },
  { name: "Donepezil 10 mg", type: "TABLET" },
  { name: "Memantine 10 mg", type: "TABLET" },
  { name: "Gingko biloba 120mg", type: "TABLET" },
  { name: "Gingko biloba 40mg", type: "TABLET" },
  { name: "Gingko biloba 80mg", type: "TABLET" },
  { name: "Gingko biloba 40mg/ml", type: "DROPS" },
  { name: "Diflunisal 500 mg", type: "CAPSULE" },
  { name: "Dipyrone �metamizole 500 mg", type: "CAPSULE" },
  { name: "Dipyrone �metamizole 500 mg", type: "TABLET" },
  { name: "Dipyrone �metamizole 500mg/ml", type: "DROPS" },
  { name: "Ibuprofen 200 mg", type: "TABLET" },
  { name: "Ibuprofen 400 mg", type: "TABLET" },
  { name: "Ibuprofen 600 mg", type: "TABLET" },
  { name: "Ibuprofen 512 mg", type: "TABLET" },
  { name: "Ibuprofen 125mg", type: "OTHER" },
  { name: "Ibuprofen 60mg", type: "OTHER" },
  { name: "Ketoprofen 50 mg", type: "CAPSULE" },
  { name: "Ketoprofen 150 mg", type: "CAPSULE" },
  { name: "Naproxen 500 mg", type: "TABLET" },
  { name: "Naproxen 275 mg", type: "TABLET" },
  { name: "Indomethacine 100 mg", type: "OTHER" },
  { name: "Indomethacine 25 mg", type: "CAPSULE" },
  { name: "Sulindac 200 mg", type: "TABLET" },
  { name: "Etodolac 400mg", type: "TABLET" },
  { name: "Etodolac 500 mg", type: "TABLET" },
  { name: "Etodolac 600mg", type: "TABLET" },
  { name: "Ketorolac 30 mg (AMP)", type: "OTHER" },
  { name: "Diclofenac Na 50mg", type: "TABLET" },
  { name: "Diclofenac Na 100mg", type: "TABLET" },
  { name: "Diclofenac Na 75mg (AMP)", type: "OTHER" },
  { name: "Diclofenac Na 50mg (AMP)", type: "OTHER" },
  { name: "Diclofenac Na 12.5mg", type: "OTHER" },
  { name: "Diclofenac K 50 mg", type: "TABLET" },
  { name: "Nabumetone 500 mg", type: "TABLET" },
  { name: "Piroxicam 20mg", type: "CAPSULE" },
  { name: "Piroxicam 20mg", type: "TABLET" },
  { name: "Piroxicam 20mg (AMP)", type: "OTHER" },
  { name: "Piroxicam - (GEL)", type: "CREAM" },
  { name: "Lornoxicam 9 mg", type: "TABLET" },
  { name: "Meloxicam 15 mg", type: "TABLET" },
  { name: "Meloxicam 7.5 mg", type: "TABLET" },
  { name: "Mefenamic Acid 500 mg", type: "TABLET" },
  { name: "Celecoxib 100 mg", type: "CAPSULE" },
  { name: "Celecoxib 200 mg", type: "CAPSULE" },
  { name: "Etrocoxib 60 mg", type: "TABLET" },
  { name: "Etrocoxib 90 mg", type: "TABLET" },
  { name: "Etrocoxib 120 mg", type: "TABLET" },
  { name: "Paracetamol 500 mg", type: "TABLET" },
  { name: "Paracetamol 1000 mg", type: "TABLET" },
  { name: "Paracetamol 150 mg", type: "OTHER" },
  { name: "Paracetamol 300 mg", type: "OTHER" },
  { name: "Paracetamol 80 mg", type: "OTHER" },
  { name: "Paracetamol 250 mg", type: "OTHER" },
  { name: "Paracetamol + Diclofenac 500 mg+50 mg", type: "TABLET" },
  { name: "Paracetamol + Caffiene 500 mg+ 65mg", type: "TABLET" },
  { name: "Paracetamol � Aspirin � Caffiene 250mg, 250mg, 65 mg", type: "TABLET" },
  { name: "Hydroxychloroquine 200 mg", type: "TABLET" },
  { name: "Sulfasalazine 500 mg", type: "TABLET" },
  { name: "Methotrexate 2.5 mg", type: "TABLET" },
  { name: "Methotrexate 50mg/2ml (VIAL)", type: "OTHER" },
  { name: "Azathioprine 50 mg", type: "TABLET" },
  { name: "Lefunomide 20 mg", type: "TABLET" },
  { name: "Colchicne .5mg", type: "TABLET" },
  { name: "Alpurinol 100 mg", type: "TABLET" },
  { name: "Oxybutynin 5mg (-)", type: "OTHER" },
  { name: "Tolterodine 2 mg", type: "TABLET" },
  { name: "Tolterodine 2 mg (?CAP)", type: "CAPSULE" },
  { name: "Solifenacin 5mg (?TAB)", type: "TABLET" },
  { name: "Solifenacin 10 mg (?TAB)", type: "TABLET" },
  { name: "Fesoterodine 4 mg (?TAB)", type: "TABLET" },
  { name: "Fesoterodine 8 mg (?TAB)", type: "TABLET" },
  { name: "Desmopressin .1mg (?TAB)", type: "TABLET" },
  { name: "Desmopressin .2mg (?TAB)", type: "TABLET" },
  { name: "Desmopressin 120mcg (?TAB)", type: "TABLET" },
  { name: "Trospium 15 mg (?TAB)", type: "TABLET" },
  { name: "Trospium 30 mg (?TAB)", type: "TABLET" },
  { name: "Imipramin 25 mg (?TAB)", type: "TABLET" },
  { name: "Amitriptylline 25 mg (?TAB)", type: "TABLET" },
  { name: "Amitriptylline 10 mg (?TAB)", type: "TABLET" },
  { name: "Diazepam 5mg (?TAB)", type: "TABLET" },
  { name: "Diazepam 2 mg (?TAB)", type: "TABLET" },
  { name: "Diazepam 10 mg (?TAB)", type: "TABLET" },
  { name: "Diazepam 10 mg (AMP)", type: "OTHER" },
  { name: "Baclofen 10mg (?TAB)", type: "TABLET" },
  { name: "Baclofen 25mg (?TAB)", type: "TABLET" },
  { name: "Tizanidine 2mg (?TAB)", type: "TABLET" },
  { name: "Tizanidine 4mg (?TAB)", type: "TABLET" },
  { name: "Orphenadrine + Paracetamol 30 mg + 500 mg", type: "TABLET" },
  { name: "Cyclopenzaprine 5mg", type: "TABLET" },
  { name: "Cyclopenzaprine 10 mg", type: "TABLET" },
  { name: "Tamsulosin .4 mg", type: "TABLET" },
  { name: "Doxazosin 1mg", type: "TABLET" },
  { name: "Doxazosin 2mg", type: "TABLET" },
  { name: "Doxazosin 4mg", type: "TABLET" },
  { name: "Alfuzocin 10 mg", type: "TABLET" },
  { name: "Alfuzocin 5 mg", type: "TABLET" },
  { name: "Cllonidine 1.5 mcg", type: "TABLET" },
  { name: "Methyl dopa 250mg", type: "TABLET" },
  { name: "Sildenafil 50 mg", type: "TABLET" },
  { name: "Sildenafil 100 mg", type: "TABLET" },
  { name: "Tadalafil 5 mg", type: "TABLET" },
  { name: "Tadalafil 10 mg", type: "TABLET" },
  { name: "Tadalafil 20 mg", type: "TABLET" },
  { name: "Vadenafil 10 mg", type: "TABLET" },
  { name: "Vadenafil 20 mg", type: "TABLET" },
  { name: "Alprostadil 20 mcg", type: "TABLET" },
  { name: "Alpurinol 300 mg", type: "TABLET" },
  { name: "Diphenhydramine 50 mg", type: "TABLET" },
  { name: "Dimenhydramine 50 mg", type: "TABLET" },
  { name: "Cinarzine 25 mg", type: "TABLET" },
  { name: "Cinarzine 75 mg", type: "TABLET" },
  { name: "Doxylamine 25 mg", type: "TABLET" },
  { name: "Chlorpheniramine 4 mg", type: "TABLET" },
  { name: "Chlorpheniramine 2 mg/5 ml", type: "SYRUP" },
  { name: "Chlorpheniramine 2 mg", type: "TABLET" },
  { name: "Dimetindene 1 mg/ml", type: "DROP" },
  { name: "Hydroxyzine 10 mg", type: "TABLET" },
  { name: "Hydroxyzine 25 mg", type: "TABLET" },
  { name: "Promethazine 25 mg", type: "TABLET" },
  { name: "Promethazine 5mg/5ml ?SYRUP", type: "SYRUP" },
  { name: "Promethazine 25mg (?AMP)", type: "OTHER" },
  { name: "Cyprohepatadine 4mg", type: "OTHER" },
  { name: "Cetrizine 10 mg", type: "OTHER" },
  { name: "Loratidine 10 mg", type: "TABLET" },
  { name: "Levocetrizine 5 mg", type: "TABLET" },
  { name: "Desloratidine 5mg", type: "TABLET" },
  { name: "Desloratidine 2.5mg/5ml", type: "SYRUP" },
  { name: "FexoFenadine 120 mg", type: "TABLET" },
  { name: "FexoFenadine 180 mg", type: "TABLET" },
  { name: "Betahistine 16 mg", type: "TABLET" },
  { name: "nan - (NAN)", type: "OTHER" },
  { name: "Famotidine 20mg", type: "TABLET" },
  { name: "Famotidine 40mg", type: "TABLET" },
  { name: "Omeprazole 20mg", type: "CAPSULE" },
  { name: "Omeprazole 40mg", type: "CAPSULE" },
  { name: "Omeprazole 10mg", type: "CAPSULE" },
  { name: "Esomeprazole 20mg", type: "CAPSULE" },
  { name: "Esomeprazole 20mg", type: "TABLET" },
  { name: "Esomeprazole 40mg", type: "CAPSULE" },
  { name: "Esomeprazole 40mg", type: "TABLET" },
  { name: "Esomeprazole 40mg (VIALS)", type: "OTHER" },
  { name: "Pantoprazole 20mg", type: "TABLET" },
  { name: "Pantoprazole 40mg", type: "TABLET" },
  { name: "Lansoprazole 30mg", type: "CAPSULE" },
  { name: "Dexlansoprazole 30mg", type: "CAPSULE" },
  { name: "Dexlansoprazole 60mg", type: "CAPSULE" },
  { name: "Misoprostol 200mg", type: "TABLET" },
  { name: "Calcium Carbonate + Magnesium Carbonate + Alginic acid 680mg+80mg (CHEWABLE TAB)", type: "OTHER" },
  { name: "Famotidine + Magnesium Hydroxide + Calcium Carbonate 10mg+165mg+800mg (CHEWABLE TAB)", type: "OTHER" },
  { name: "Sodium Alginate + Calcium Carbonate + Hydrogen Carbonate 50mg+16mg+26.7mg/ml (SUSPENSION)", type: "OTHER" },
  { name: "Magnesium Hydroxide + Aluminum Hydroxide 225mg+200mg/5ml (SUSPENSION)", type: "OTHER" },
  { name: "Magnesium Hydroxide + Aluminum Hydroxide + Semithicone 200mg+200mg+25mg/5ml (SUSPENSION)", type: "OTHER" },
  { name: "Citric Acid + Sodium Bicarbonate + Tartaric acid - (SACHETS)", type: "OTHER" },
  { name: "Metoclopramide 10mg", type: "TABLET" },
  { name: "Metoclopramide 10mg/2ml (AMP)", type: "OTHER" },
  { name: "Domperidone 10mg", type: "TABLET" },
  { name: "Meclizine + Pyridoxine 25mg+50mg", type: "TABLET" },
  { name: "Doxylamine + Pyridoxine 10mg+10mg", type: "TABLET" },
  { name: "Dimenhydrinate 50mg", type: "TABLET" },
  { name: "Ondansetron 4mg", type: "TABLET" },
  { name: "Ondansetron 8mg", type: "TABLET" },
  { name: "Ginger + Pyridoxine - (-)", type: "OTHER" },
  { name: "Ginger 340mg (30 CAPS)", type: "OTHER" },
  { name: "Mebeverine 135mg", type: "TABLET" },
  { name: "Hyoscine N butyl Br 10mg", type: "TABLET" },
  { name: "Hyoscine N butyl Br 20mg (AMP)", type: "OTHER" },
  { name: "Hyoscine N butyl Br + Paracetamol 10mg+250mg", type: "TABLET" },
  { name: "Mebeverine + Sulpride 100mg+25mg", type: "TABLET" },
  { name: "Sulpride 50mg", type: "TABLET" },
  { name: "Sulpride 200mg", type: "TABLET" },
  { name: "Chlorodiazopoxide � Clidinium 5mg +2.5mg (-)", type: "OTHER" },
  { name: "Activated Charcoal + senna + sulfur + rhei extract 180mg+105mg+50mg+25mg (-)", type: "OTHER" },
  { name: "Activated Charcoal + Semithicone 140mg+45mg (-)", type: "OTHER" },
  { name: "Semithicone 125mg (-)", type: "OTHER" },
  { name: "Semithicone 80mg", type: "TABLET" },
  { name: "Semithicone 40mg/ml", type: "SYRUP" },
  { name: "Mesalazine 500mg (-)", type: "OTHER" },
  { name: "Loperamide 2mg", type: "CAPSULE" },
  { name: "Kaolin + Pectin + Furazoldine -", type: "TABLET" },
  { name: "ORS - (SACHETS)", type: "OTHER" },
  { name: "Bismuth subsalicylate -", type: "TABLET" },
  { name: "Bismuth subsalicylate - (SUSPENSION)", type: "OTHER" },
  { name: "Senna Extract - (SUSP)", type: "OTHER" },
  { name: "Biscodyl 5 mg", type: "TABLET" },
  { name: "Phenolphthalein 120 mg", type: "TABLET" },
  { name: "Lactulose - (SUSP)", type: "OTHER" },
  { name: "PEG -", type: "OTHER" },
  { name: "Macrogel -", type: "OTHER" },
  { name: "Plantago + Ispaghula + Senna -", type: "OTHER" },
  { name: "Plantago + Ispaghula -", type: "OTHER" },
  { name: "Plantago + Ispaghula -", type: "CAPSULE" },
  { name: "nan nan (NAN)", type: "OTHER" },
  { name: "Bromocriptine -", type: "TABLET" },
  { name: "Cabergoline -", type: "TABLET" },
  { name: "Levothyroxine -", type: "TABLET" },
  { name: "Propyl Thiouracil - PTU -", type: "TABLET" },
  { name: "Methimazole 50 mg", type: "TABLET" },
  { name: "Alendronate -", type: "TABLET" },
  { name: "Risedronate -", type: "TABLET" },
  { name: "Hydrocortisone -", type: "TABLET" },
  { name: "Prednisolone -", type: "TABLET" },
  { name: "Triamcinolone - (VIAL)", type: "OTHER" },
  { name: "Methyl prednisolone -", type: "TABLET" },
  { name: "Methyl prednisolone - (VIAL)", type: "OTHER" },
  { name: "Betamethasone -", type: "TABLET" },
  { name: "Dexamethasone -", type: "TABLET" },
  { name: "Mesterolone -", type: "TABLET" },
  { name: "Bicalutamide -", type: "TABLET" },
  { name: "Finasteride -", type: "TABLET" },
  { name: "Dutasteride -", type: "CAPSULE" },
  { name: "Finasteride + Tamsulisin -", type: "CAPSULE" },
  { name: "Clomiphene -", type: "TABLET" },
  { name: "Tamoxifen -", type: "TABLET" },
  { name: "Estradiol -", type: "TABLET" },
  { name: "Estradiol - Norgestrel -", type: "TABLET" },
  { name: "estradiol norethisterone -", type: "TABLET" },
  { name: "Medroxy Progesterone -", type: "TABLET" },
  { name: "Progestreone -", type: "TABLET" },
  { name: "Progestreone -", type: "OTHER" },
  { name: "Dydrogesterone -", type: "TABLET" },
  { name: "HydroxyProgesterone - (AMPOULE)", type: "OTHER" },
  { name: "Allylestrenol -", type: "TABLET" },
  { name: "Northisterone -", type: "TABLET" },
  { name: "Urofollitropin FSH - (VIAL)", type: "OTHER" },
  { name: "Follitropin alpha FSH - (VIAL)", type: "OTHER" },
  { name: "\"LH + FSH \"\"HMG\"\" - (AMP)\"", type: "OTHER" },
  { name: "Human Chorionic Gonadotropins - (VIAL)", type: "OTHER" },
  { name: "Human Chorionic Gonadotropins - (AMP)", type: "OTHER" },
  { name: "Human Chorionic Gonadotropins - (PREFILLED SYRINGE)", type: "OTHER" },
  { name: "nan nan (NAN)", type: "OTHER" },
  { name: "Gestodene + Ethinyl Estradiol Oral (,075 MG+ ,03 MG)", type: "OTHER" },
  { name: "Levonorgestrel � Ethinyl Estradiol nan (-)", type: "OTHER" },
  { name: "Drospirenone - Ethinyl Estradiol nan (-)", type: "OTHER" },
  { name: "Gestodene + Ethinyl Estradiol nan (,075 MG+ ,02 MG)", type: "OTHER" },
  { name: "Chlormadinon - Ethinyl Estradiol nan (-)", type: "OTHER" },
  { name: "Cyprotrtone - Ethinyl Estradiol nan (-)", type: "OTHER" },
  { name: "Ethinyl Estradiol desogestrel nan (-)", type: "OTHER" },
  { name: "Levonorgestrel nan (-)", type: "OTHER" },
  { name: "Desogestrel nan (-)", type: "OTHER" },
  { name: "Medroxy Progesterone Inj (-)", type: "OTHER" },
  { name: "nan nan (NAN)", type: "OTHER" },
  { name: "Fusidic acid 2%", type: "CREAM" },
  { name: "Fusidic acid + Betamethasone 2% + 0.1%", type: "CREAM" },
  { name: "Fusidic acid + Hydrocortisone 2% + 1%", type: "CREAM" },
  { name: "Mupirocin 2% (OINTMENT)", type: "CREAM" },
  { name: "Silver sulfadiazine 1%", type: "CREAM" },
  { name: "Betamethasone valerate 0.1% (CREAM / OINT / LOTION)", type: "CREAM" },
  { name: "Betamethasone dipropionate 0.05% (CREAM / OINT / LOTION)", type: "CREAM" },
  { name: "Betamethasone + Salicylic acid - (OINTMENT / LOTION)", type: "OTHER" },
  { name: "Hydrocortisone 1% (CREAM / OINT)", type: "CREAM" },
  { name: "Hydrocortisone 1% (CREAM / OINT)", type: "CREAM" },
  { name: "Triamcinolone 0.1% (CREAM / OINT)", type: "CREAM" },
  { name: "Clobetasol propionate 0.05%", type: "CREAM" },
  { name: "Mometasone furoate 0.1%", type: "CREAM" },
  { name: "Permethrin 5%", type: "CREAM" },
  { name: "Diclofenac sodium 1% / 2% (GEL)", type: "CREAM" },
  { name: "Ketoprofen 2.5% (GEL)", type: "CREAM" },
  { name: "Piroxicam 0.5% (GEL)", type: "CREAM" },
  { name: "Clotrimazole 1%", type: "CREAM" },
  { name: "Terbinafine 1%", type: "CREAM" },
  { name: "Miconazole 2%", type: "CREAM" },
  { name: "Acyclovir 5%", type: "CREAM" },
  { name: "Metronidazole 0.75% (GEL)", type: "CREAM" },
  { name: "Salicylic acid - (SOLUTION / OINTMENT)", type: "OTHER" },
  { name: "Minoxidil 2% / 5% (SOLUTION (SPRAY))", type: "OTHER" },
  { name: "Xylometazoline 0.05% / 0.1% (NASAL DROPS / SPRAY)", type: "OTHER" },
  { name: "Oxymetazoline 0.025% / 0.05% (NASAL DROPS / SPRAY)", type: "OTHER" },
  { name: "Chloramphenicol 0.5% / 1% (EYE DROPS / EYE OINTMENT)", type: "OTHER" },
  { name: "Gentamicin 0.3% (EYE / EAR DROPS)", type: "OTHER" },
  { name: "Ciprofloxacin 0.3% (EYE DROPS / EYE OINTMENT)", type: "OTHER" },
  { name: "Tobramycin 0.3% (EYE DROPS / EYE OINTMENT)", type: "OTHER" },
  { name: "Ofloxacin 0.3% (EYE DROPS)", type: "OTHER" },
  { name: "Sodium hyaluronate - (EYE DROPS (ARTIFICIAL TEARS))", type: "OTHER" },
  { name: "nan nan (NAN)", type: "OTHER" },
  { name: "Multivitamin + Minerals -", type: "CAPSULE" },
  { name: "Multivitamin + Ginseng -", type: "CAPSULE" },
  { name: "Vitamin B1 + B6 + B12 -", type: "TABLET" },
  { name: "Multivitamin + Iron", type: "SYRUP" },
  { name: "Multivitamin + Iron -", type: "CAPSULES" },
  { name: "Vitamin B1 + B6 + B12 - ( AMPOULES)", type: "OTHER" },
  { name: "Vitamin B12 (Cyanocobalamin) 1000mcg (AMPOULES)", type: "OTHER" },
  { name: "Vitamin B Complex -", type: "TABLET" },
  { name: "Vitamin C (Ascorbic Acid) 500mg / 1000mg", type: "TABLET" },
  { name: "Vitamin D3 (Cholecalciferol) 400IU / 1000IU / 5000IU / 50000IU (TABLETS / DROPS / AMPOULES)", type: "OTHER" },
  { name: "Calcium + Vitamin D3 600mg + 400IU", type: "TABLET" },
  { name: "Folic Acid 1mg / 5mg", type: "TABLET" },
  { name: "Ferrous Sulfate (Iron) 200mg", type: "TABLET" },
  { name: "Omega 3 (Fish Oil) 1000mg", type: "CAPSULE" },
  { name: "Glucosamine + Chondroitin -", type: "TABLET" },
  { name: "Zinc Sulfate 20mg/50 mg", type: "SYRUP" },
  { name: "Zinc Sulfate 20mg/50 mg", type: "OTHER" },
  { name: "Magnesium -", type: "TABLET" },
  { name: "Biotin 5 mg", type: "TABLET" },
  { name: "Fusidic acid 2 %", type: "CREAM" },
  { name: "Fusidic acid 2 % (OINTMENT)", type: "CREAM" }  ];

  for (const med of medicinesToAdd) {
    try {
      await prisma.medicine.upsert({
        where: { name: med.name },
        update: { type: med.type },
        create: {
          name: med.name,
          type: med.type,
        },
      });
      console.log(`✅ Medicine "${med.name}" added/updated.`);
    } catch (e) {
      console.error(`⚠️ Could not create/update medicine "${med.name}":`, e.message);
    }
  }

}

main()
  .catch((e) => {
    // Log the error message clearly
    console.log('FATAL SEEDING ERROR:', e.message);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    console.log('--- Seeding Finished ---');
  });